version: "2"
services:

  application:
    container_name: polymaker
    build: .
    volumes:
     - .:/root
    ports:
     - 4000:4000
    links:
     - database

  jupyter:
    container_name: notebook
    image: jupyter/minimal-notebook:latest
    ports:
     - 8888:8888
    links:
     - database

  database:
    container_name: mongodb
    entrypoint: mongod
    image: mongo:3.0.2
    ports:
     - 27017:27017
