app:
  container_name: polymaker
  build: .
  volumes:
   - .:/root
  ports:
   - 5000:5000
  links:
   - db

jupyter:
  container_name: notes
  image: jupyter/minimal-notebook:latest
  ports:
   - 8888:8888
  links:
   - db

db:
  container_name: mongo
  image: mongo:3.0.2
  ports:
   - 27017:27017
